### ISSUE TITLE
Help setting up Jellyscrub

### ISSUE THREAD

**Issue by MaxPuig** [nicknsy/jellyscrub#117]
Currently, after adding the jellyscrub plugin, and creating all .bif files, only the Jellyfin chapter previews appear.
**See end of text for my question.**

## My installation and configuration
I used the following commands to set up Jellyfin on my **Raspberry Pi**:
> curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash
> wget -O- https://repo.jellyfin.org/install-debuntu.sh | sudo bash

And added the plugin by adding this repo URL in the plugins tab on Jellyfin through the browser and installed it
> https://raw.githubusercontent.com/nicknsy/jellyscrub/main/manifest.json

My configuration:
```
HW Acceleration: None
Generate trickplay files on demand when a client requests one: ON
Save trickplay files within media folders: OFF
Create trickplays when videos are discovered: ON
Scan Behavior: Non Blocking
Inject client script into jellyfin-web: ON
Image Interval: 1000
Width Resolutions: 320
Process Priority: Below Normal
FFmpeg Threads: -1
```

From the README, I believe this applies to me:
> Install from distro repositories - the jellyfin-server will execute as jellyfin user while the web files will be owned by root, www-data, etc. This can likely be fixed by adding the jellyfin (or whichecher user your main jellyfin server runs at) to the same group the jellyfin-web folders are owned by. You should only do this if they are owned by a group other than root, and will have to lookup how to manage permissions on your specific distro.

## Question
Could you please elaborate a bit more on how to change permissions?
I'm pretty sure `jellyfin` is the user that runs Jellyfin. I've checked using the `htop` command.
**I don't know what `jellyfin-web` folders you are referring to**. 
The way I would check who the owner of the `jellyfin-web` folder is, would be by using `ls -la`. 

What command should I then use to add the user Jellyfin to the group? 
- `usermod -a -G jellyfin-web jellyfin`

**Comment by nicknsy** [comment]
Could you please paste the parts of your jellyfin logs relating to jellyscrub and script injection status? It should also print the location of the web files in logs.

**Comment by MaxPuig** [comment]
Here are the logs which I believe to be relevant. I added the lines which include the word “jellyscrub” and the lines in which I manually trigger the “Generate BIF Files” job and play a movie. Let me know If you need anything else, or the entire log.

```
[2023-08-03 21:26:00.470 +02:00] [INF] Loaded assembly "Nick.Plugin.Jellyscrub, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/Jellyscrub_1.1.1.0/Nick.Plugin.Jellyscrub.dll"

[2023-08-03 21:26:49.133 +02:00] [ERR] Encountered exception while writing to "/usr/share/jellyfin/web/index.html": "System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Nick.Plugin.Jellyscrub.JellyscrubPlugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, ILogger`1 logger, IServerConfigurationManager configurationManager)"
[2023-08-03 21:26:49.215 +02:00] [INF] Loaded plugin: "Jellyscrub" "1.1.1.0"

[2023-08-03 23:33:50.616 +02:00] [INF] Executing "Generate BIF Files"
[2023-08-03 23:33:55.748 +02:00] [INF] "Generate BIF Files" Completed after 0 minute(s) and 5 seconds
[2023-08-03 23:33:55.751 +02:00] [INF] ExecuteQueuedTasks
[2023-08-03 23:34:25.651 +02:00] [INF] User policy for "mecs". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2023-08-03 23:34:25.653 +02:00] [INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/mnt/nas/Movies/Peliculas EN/Godzilla Vs. Kong 2021 1080p.mp4", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/4c2f62fb-ccfa-0b7d-1b37-76eb2db04148/stream.mp4?MediaSourceId=4c2f62fbccfa0b7d1b3776eb2db04148&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=19f16be4d89b8a3815011a6e14ecfbbe"
[2023-08-03 23:34:36.984 +02:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.8.10" playing "Godzilla vs. Kong". Stopped at "7122" ms
[2023-08-03 23:34:39.081 +02:00] [INF] AuthenticationScheme: "CustomAuthentication" was forbidden.
```

**Comment by nicknsy** [comment]
Okay, so it looks like jellyfin process doesn't have write access to /usr/share/jellyfin/web/. If you do ls -la /usr/share/jellyfin/web/ what are the permissions?

**Comment by MaxPuig** [comment]
All of them are:
`-rw-r--r-- 1 root root`
Exceptuating these folders:
`drwxr-xr-x 5 root root    4096 Mar 18 16:10 assets`
`drwxr-xr-x 3 root root    4096 Apr 24 01:53 libraries`
`drwxr-xr-x 8 root root    4096 Mar 18 16:10 themes`

**Comment by nicknsy** [comment]
Do chmod -R jellyfin:jellyfin /usr/share/jellyfin/web/ then restart jellyfin and see if the script injection succeeds using the logs.

**Comment by MaxPuig** [comment]
```
pi@raspberrypi:~ $ sudo chmod -R --verbose jellyfin:jellyfin /usr/share/jellyfin/web/ 
chmod: invalid mode: ‘jellyfin:jellyfin’
Try 'chmod --help' for more information.
```
I get this. The user exists, which is weird.

**Comment by nicknsy** [comment]
Woops I meant ```chown``` not chmod.

**Comment by MaxPuig** [comment]
Spectacular, thanks! That worked :)

**Comment by dandud100** [comment]
`chown jellyfin:jellyfin /usr/share/jellyfin/web/index.html` and `chmod 666 /usr/share/jellyfin/web/index.html` with the docker console within unraid did the job for me.

**Comment by Alexmen97** [comment]
@dandud100 I entered the two commands on the jellyfin docker terminal but it doesn't work. I use unraid

**Comment by dandud100** [comment]
> @dandud100 I entered the two commands on the jellyfin docker terminal but it doesn't work. I use unraid

Restart the docker container.

**Comment by Alexmen97** [comment]
sorry for my English.
I did what you told me but it doesn't work.
should I remove these settings from jellyfin docker? look at photo
![Screenshot 2024-01-18 102318](https://github.com/nicknsy/jellyscrub/assets/16058330/deff31f4-6f2d-4fde-8a02-0a2e865e8502)

**Comment by dandud100** [comment]
> sorry for my English. I did what you told me but it doesn't work. should I remove these settings from jellyfin docker?

No, dont remove them. 

Please input the following console output to the docker console of your jellyfin, scroll down to index.php and send a screenshot:
`ls -la /usr/share/jellyfin/web/`

**Comment by Alexmen97** [comment]
I did as you told me but I see that the number in the central line is different
![Screenshot 2024-01-18 111213](https://github.com/nicknsy/jellyscrub/assets/16058330/9e48b46c-c83f-41b6-85e6-a768ae8ef8e8)


in the image below I have set jellyscrub like this
![Screenshot 2024-01-18 111810](https://github.com/nicknsy/jellyscrub/assets/16058330/c10339ca-38b7-4900-a888-84cbd8b16137)

**Comment by Alexmen97** [comment]
I solved it, I had jellyfin set as root.
Thanks so much for the support @dandud100

**Comment by dandud100** [comment]
> I solved it, I had jellyfin set as root. Thanks so much for the support @dandud100

Nice to hear! The next step would be making this change persistive, i wrote a guide for it, but it is in german. Maybe it can still help you in some way: https://forums.unraid.net/topic/149537-nutzt-hier-jemand-jellyscrub-f%C3%BCr-jellyfin-wie-funktioniert-die-dauerhafte-berechtigungs%C3%A4nderung-der-indexhtml/?do=findComment&comment=1342117
