### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by archive-r** [nicknsy/jellyscrub#124]
Hi,

All my media files are failing jellyscrub with the following error.

```
[2023-10-16 18:12:05.353 +00:00] [ERR] [23] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Error while creating BIF file
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Boolean> MediaBrowser.Common.Extensions.ProcessExtensions.WaitForExitAsync(System.Diagnostics.Process, System.TimeSpan)'.
   at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.ExtractVideoImagesOnInterval(String inputFile, String container, MediaStream videoStream, MediaSourceInfo mediaSource, Nullable`1 threedFormat, TimeSpan interval, String targetDirectory, String filenamePrefix, Int32 maxWidth, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.ExtractVideoImagesOnInterval(String inputFile, String container, MediaStream videoStream, MediaSourceInfo mediaSource, Nullable`1 threedFormat, TimeSpan interval, String targetDirectory, String filenamePrefix, Int32 maxWidth, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
```

Below is the contents of my docker yaml file.

```
  jellyfin:
    image: jellyfin/jellyfin:unstable
    container_name: jellyfin
    group_add:
      - "105"
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - /media/hoon:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    network_mode: host
```

Also, I am using ubuntu 23.04, intel n100 cpu.

**Comment by archive-r** [comment]
Using jellyfin stable solves the problem.
