### ISSUE TITLE
Jellyscrub crashes while creating BIF file

### ISSUE THREAD

**Issue by ericswpark** [nicknsy/jellyscrub#134]
I'm running Jellyfin 10.8.13 with Jellyscrub 3.1.1.0. I noticed the following while checking the logs:

```
[2023-12-17 13:50:11.641 +09:00] [INF] [137] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Creating trickplay files at 320 width, for "/data/media/TVShows/Adam Ruins Everything/Season 01/adam.ruins.everything.s01e18.720p.mkv" [ID: 96f1d6ec-9f92-391c-dfc8-05eb9eb9bc3e]
[2023-12-17 13:50:11.641 +09:00] [ERR] [137] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Error while creating BIF file
System.InvalidOperationException: EncodingHelper returned empty or invalid filter parameters.
   at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.ExtractVideoImagesOnInterval(String inputFile, String container, MediaStream videoStream, MediaSourceInfo mediaSource, Nullable`1 threedFormat, TimeSpan interval, String targetDirectory, String filenamePrefix, Int32 maxWidth, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
```

**Comment by decisoft** [comment]
Hi there,

I'm running the same issue, only with one 4K movie (no problem with other UHD movies/series, or FHD movies/series), and the same error you have, "killing due to inactivity":

`[2024-01-02 12:37:58.809 +00:00] [INF] [45] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Killing ffmpeg process due to inactivity.
[2024-01-02 12:37:59.830 +00:00] [INF] [45] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Killing process ""ffmpeg""
[2024-01-02 12:37:59.833 +00:00] [ERR] [45] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: ffmpeg image extraction failed for /data/movies-4k/movie/movie-4k WEBDL-2160p h265 EAC3[ES+EN] [ES+EN].mkv
[2024-01-02 12:37:59.892 +00:00] [ERR] [45] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Error while creating BIF file`


Has been that for weeks now.
