### ISSUE TITLE
Bug: Scrub scheduler did not ignore its own folder.

### ISSUE THREAD

**Issue by davidngrc** [nicknsy/jellyscrub#135]
My plugin is on 1.1.1.0
I have this plugin long time ago, and upgrade to the above version.
and in the jellyfin log, I find below error.
it seems this plugin did not ignore its own folder.
is it possible to add a "ignore folder list" and "ignore filename list"?
thank you.

`System.UnauthorizedAccessException: Access to the path '/Film/Movie/1989/Millennium (1989)/trickplay' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)`

**Comment by nicknsy** [comment]
Closing due to inactivity. This is a permissions error due to the process running jellyfin not having access to the folders which contain the media. Either add the jellyfin user as an owner, run jellyfin as root (in docker), or change jellyscrub to save to metadata (if still using 10.8).
