### ISSUE TITLE
Generating bif files shown as 100% complete, however it hasnt generated them all

### ISSUE THREAD

**Issue by PeachesMLG** [nicknsy/jellyscrub#145]
The scheduled task to Generate bif files is shown as 100% complete, however it hasnt even generated 10% of them

**Comment by PeachesMLG** [comment]
```

[2024-03-12 02:59:59.998 +00:00] [INF] [145] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Generate BIF Files"
[2024-03-12 03:00:00.178 +00:00] [INF] [145] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Creating trickplay files at 420 width, for "/data/tvshows/The Rookie/Season 2/The Rookie - S02E09 - Breaking Point.mkv" [ID: 144049eb-46d1-7164-25d8-654311daca1b]
[2024-03-12 03:00:00.178 +00:00] [INF] [145] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda -threads 1 -autorotate 0 -i file:"/data/tvshows/The Rookie/Season 2/The Rookie - S02E09 - Breaking Point.mkv" -autoscale 0 -an -sn -vf "fps=1/10,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_cuda=w=420:h=236:format=yuv420p,hwdownload,format=yuv420p" -threads 0 -c:v mjpeg -f image2 "/cache/temp/4d47a9bbbef54f468fca0f6262dbc798/img_%08d.jpg"
[2024-03-12 03:00:00.179 +00:00] [INF] [145] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Setting generation process priority to Normal
[2024-03-12 03:00:00.210 +00:00] [ERR] [142] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Error while creating BIF file
System.InvalidOperationException: Cannot make BIF file from 0 images.
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
   ```

**Comment by nicknsy** [comment]
> ```
> 
> 
> 
> [2024-03-12 02:59:59.998 +00:00] [INF] [145] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Generate BIF Files"
> 
> [2024-03-12 03:00:00.178 +00:00] [INF] [145] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Creating trickplay files at 420 width, for "/data/tvshows/The Rookie/Season 2/The Rookie - S02E09 - Breaking Point.mkv" [ID: 144049eb-46d1-7164-25d8-654311daca1b]
> 
> [2024-03-12 03:00:00.178 +00:00] [INF] [145] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: /usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device cuda=cu:0 -filter_hw_device cu -hwaccel cuda -hwaccel_output_format cuda -threads 1 -autorotate 0 -i file:"/data/tvshows/The Rookie/Season 2/The Rookie - S02E09 - Breaking Point.mkv" -autoscale 0 -an -sn -vf "fps=1/10,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_cuda=w=420:h=236:format=yuv420p,hwdownload,format=yuv420p" -threads 0 -c:v mjpeg -f image2 "/cache/temp/4d47a9bbbef54f468fca0f6262dbc798/img_%08d.jpg"
> 
> [2024-03-12 03:00:00.179 +00:00] [INF] [145] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Setting generation process priority to Normal
> 
> [2024-03-12 03:00:00.210 +00:00] [ERR] [142] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Error while creating BIF file
> 
> System.InvalidOperationException: Cannot make BIF file from 0 images.
> 
>    at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
> 
>    at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
> 
>    ```

Is this just a single error or does this show for every video?

**Comment by PeachesMLG** [comment]
Every video, repeated 1000+ times

**Comment by PeachesMLG** [comment]
Also, the videos work fine, they arnt corrupted and they play fine, so not sure why it says it has 0 images

**Comment by memehammad** [comment]
Had the same issue. Fixed it by switching hw acceleration from "Full" to "No Encode"

**Comment by nicknsy** [comment]
Yes, this happens if ffmpeg exits before generating images which is usually due to misconfigured hardware acceleration settings.

**Comment by PeachesMLG** [comment]
huh, funnily enough I ran it again today, and its currently generated 1k/8k (before it did like 200 maybe) so :shrug:

**Comment by PeachesMLG** [comment]
Im going to close this, Ive had issues with my docker gpu passthrough where the passthrough will randomly fail after a certain time, and restarting the docker instance will fix it, this is potentially a result of that issue.

**Comment by nicknsy** [comment]
> Im going to close this, Ive had issues with my docker gpu passthrough where the passthrough will randomly fail after a certain time, and restarting the docker instance will fix it, this is potentially a result of that issue.

I don't know if this might apply to you, but I also had a lot of passthrough problems when I was suspending/sleeping the system instead of shutting it down fully when I wasn't using it.
