### ISSUE TITLE
[10.9.0] MissingMethodException

### ISSUE THREAD

**Issue by Silvenga** [nicknsy/jellyscrub#148]
```
[19:27:43] [ERR] [132] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Error while creating BIF file
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Boolean> MediaBrowser.Common.Extensions.ProcessExtensions.WaitForExitAsync(System.Diagnostics.Process, System.TimeSpan)'.
   at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.ExtractVideoImagesOnInterval(String inputFile, String container, MediaStream videoStream, MediaSourceInfo mediaSource, Nullable`1 threedFormat, TimeSpan interval, String targetDirectory, String filenamePrefix, Int32 maxWidth, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.ExtractVideoImagesOnInterval(String inputFile, String container, MediaStream videoStream, MediaSourceInfo mediaSource, Nullable`1 threedFormat, TimeSpan interval, String targetDirectory, String filenamePrefix, Int32 maxWidth, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
```

Relates to: https://github.com/nicknsy/jellyscrub/issues/124

---

I think this method now exists in the BCL, so that's likely the easiest fix.

**Comment by Silvenga** [comment]
Of course I missed the README update.
