### ISSUE TITLE
Error crating Trickplay files

### ISSUE THREAD

**Issue by wuast94** [nicknsy/jellyscrub#60]
When i try to create the BIF files i get this error

```
[17:08:15] [INF] [160] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Generate BIF Files
[17:08:15] [INF] [160] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Creating trickplay files at 320 width, for /media/Dokus/exampledoku/exampledoku.mkv [ID: 005b990d-a9aa-b4ec-7ec3-8b932816730a]
[17:08:15] [INF] [160] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: /usr/lib/jellyfin-ffmpeg/ffmpeg -f matroska,webm -threads 0 -i file:"/media/Dokus/exampledoku/exampledoku.mkv" -threads 0 -v quiet -filter:v fps=1/0,scale=min(iw\,320):trunc(ow/dar/2)*2 -f image2 "/cache/temp/d6735445664141cead8f949e95fa7cf1/img_%08d.jpg"
[17:08:15] [INF] [160] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Setting generation process priority to BelowNormal
[17:08:46] [INF] [159] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Killing ffmpeg process
[17:08:46] [ERR] [159] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: ffmpeg image extraction failed for file:"/media/Dokus/exampledoku/exampledoku.mkv"
[17:08:46] [ERR] [159] Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask: Error creating trickplay files for Shiny_Flakes: The Teenage Drug Lord: MediaBrowser.Common.FfmpegException: ffmpeg image extraction failed for file:"/media/Dokus/exampledoku/exampledoku.mkv"
   at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.ExtractVideoImagesOnInterval(String inputFile, String container, MediaStream videoStream, MediaSourceInfo mediaSource, Nullable`1 threedFormat, TimeSpan interval, String targetDirectory, String filenamePrefix, Int32 maxWidth, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
```

**Comment by nicknsy** [comment]
"Killing ffmpeg process" means the process was terminated due to hang protection, which occurs when a single image hasn't been extracted within 30 seconds.
