### ISSUE TITLE
Trickplay Error: System.IO.IOException: Read-only file system

### ISSUE THREAD

**Issue by YaBoiHuni** [nicknsy/jellyscrub#66]
Version: 10.8.9
Operating System: Unraid v6.11.5
Architecture: X64
Jellyscrub: 1.0.0.7 Installed via plugin repository within Jellyfin (which is running on a docker container)

Turned on "Save trickplay files within media folders" to make it easier to manage the storage of the files. Unfortunately, I am immediately hit with this error when trying to generate the files.

> [17:39:08] [INF] [151] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Creating trickplay files at 320 width, for /JF_SERIES/4K/Yellowstone (2018)/Season 5/Yellowstone (2018) - S05E06 - Cigarettes, Whiskey, a Meadow and You WEBDL-2160p.mkv [ID: 97220f76-3f85-8d77-62b8-7d07e67227eb]
[17:39:08] [INF] [151] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: /usr/lib/jellyfin-ffmpeg/ffmpeg -f matroska,webm -threads 0 -i file:"/JF_SERIES/4K/Yellowstone (2018)/Season 5/Yellowstone (2018) - S05E06 - Cigarettes, Whiskey, a Meadow and You WEBDL-2160p.mkv" -threads 0 -v quiet -filter:v fps=1/10,scale=min(iw\,320):trunc(ow/dar/2)*2 -f image2 "/cache/temp/d9fe516ef81f476f94839fd02ac5d1e6/img_%08d.jpg"
[17:39:08] [INF] [151] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Setting generation process priority to BelowNormal
[17:46:50] [ERR] [229] Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask: Error creating trickplay files for Cigarettes, Whiskey, a Meadow and You: System.IO.IOException: Read-only file system : '/JF_SERIES/4K/Yellowstone (2018)/Season 5/trickplay'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, CancellationToken cancellationToken)
   at Nick.Plugin.Jellyscrub.ScheduledTasks.BIFGenerationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
[17:46:50] [INF] [229] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Creating trickplay files at 320 width, for /JF_SERIES/4K/Yellowstone (2018)/Season 5/Yellowstone (2018) - S05E04 - Horses in Heaven WEBDL-2160p.mkv [ID: 1265713d-2415-f50a-9d34-3a7ed39d25dd]
[17:46:50] [INF] [229] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: /usr/lib/jellyfin-ffmpeg/ffmpeg -f matroska,webm -threads 0 -i file:"/JF_SERIES/4K/Yellowstone (2018)/Season 5/Yellowstone (2018) - S05E04 - Horses in Heaven WEBDL-2160p.mkv" -threads 0 -v quiet -filter:v fps=1/10,scale=min(iw\,320):trunc(ow/dar/2)*2 -f image2 "/cache/temp/65772f606dd44427a7a7fcda50932d73/img_%08d.jpg"
[17:46:50] [INF] [229] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Setting generation process priority to BelowNormal
[17:53:11] [INF] [37] Emby.Server.Implementations.ScheduledTasks.TaskManager: Attempting to cancel Scheduled Task Generate BIF Files
[17:53:20] [INF] [47] Emby.Server.Implementations.ScheduledTasks.TaskManager: Generate BIF Files Completed after 20 minute(s) and 49 seconds
[17:53:20] [INF] [47] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks

Originally the share it was writing to was set to private. So I changed it to public and still has the same issue. Not sure what I need to do to enable write perms for JellySrub to write to the media folder.

Thank you

**Comment by YaBoiHuni** [comment]
> I'm not sure how Unraid works but have you restarted the jellyfin container so the share can be remounted with correct permissions?

Yeah, I tried that as well. Still having the same issue.

**Comment by nicknsy** [comment]
Is there a separate read-only setting you have checked in the share besides just public/private/secure access?

**Comment by YaBoiHuni** [comment]
There is an option for specific read-only & read/write access when using private/secure, on a per-user basis. That does not show up when using "Public" however.

**Comment by nicknsy** [comment]
Hmm well I can't think of anything else. Since this is an issue with unraid I'd suggest making a post on their forums with more detailed info about the share--maybe there's some odd behavior with certain filesystems or share types that they would know about.
