### ISSUE TITLE
Error dealing with wrong Jellyfin version

### ISSUE THREAD

**Issue by tetebueno** [nicknsy/jellyscrub#93]
Hi, I can't get the plugin to work. I'm seeing the following in the log file when server starts:

```
Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/plugins/Jellyscrub_1.0.0.9/Nick.Plugin.Jellyscrub.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MediaBrowser.Common, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
```

I'm using version 1.0.0.9 in Jellyfin 10.8.0 under Docker in Linux and I had to enable it by editing `index.html` file manually.

Let me know forma any additional info I can providencial.

Thanks.

**Comment by nicknsy** [comment]
This is a mistake with the dependency set specifically to 10.8.4 instead of 10.8.*. If you would like to use the plugin you can upgrade jellyfin to at least 10.8.4 or wait until I do a plugin update.

**Comment by tetebueno** [comment]
Just updated to latest version (`10.8.9`) and it just worked. I'll change the title of the issue so it helps anybody else bumping.

Thanks a lot and congratulations, awesome project.
